version: "3.7"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioaccesskey
      - MINIO_ROOT_PASSWORD=miniosecretkey
    ports:
      - "9020:9000" # API MinIO
      - "9001:9001" # Web UI MinIO
    networks:
      - my_network
    volumes:
      - minio_data:/data
    labels:
      - "traefik.enable=true"

      # API MinIO
      - "traefik.http.routers.minio-api.rule=Host(`minio.mia-services.fr`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls.certresolver=myresolver"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"

      # Web UI MinIO
      - "traefik.http.routers.minio-ui.rule=Host(`minio-ui.mia-services.fr`)"
      - "traefik.http.routers.minio-ui.entrypoints=websecure"
      - "traefik.http.routers.minio-ui.tls.certresolver=myresolver"
      - "traefik.http.services.minio-ui.loadbalancer.server.port=9001"

    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio_data:

networks:
  my_network:
    external: true
