services:
  convertissor_backend:
    container_name: convertissor_backend_container
    image: hermesn/convertissor_backend:latest
    mem_limit: 1G
    ports:
      - "5500:5500"
    environment:
      NODE_ENV: "production"
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertissor_backend.rule=host(`convertisseur-api.mia-services.fr`)"
      - "traefik.http.routers.convertissor_backend.entrypoints=websecure"
      - "traefik.http.services.convertissor_backend.loadbalancer.server.port=5500"
      - "traefik.http.routers.convertissor_backend.tls.certresolver=myresolver"

networks:
  my_network:
    external: true
