services:
  convertissor_backend:
    container_name: convertissor_backend_container
    image: hermesn/convertissor_backend:latest
    ports:
      - "5500:5500"
    environment:
      NODE_ENV: "production"
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertissor_backend.rule=host(`api.convertisseur.mia-services.fr`)"
      - "traefik.http.routers.convertissor_backend.entrypoints=websecure"
      - "traefik.http.services.convertissor_backend.loadbalancer.server.port=5500"
      - "traefik.http.routers.convertissor_backend.tls.certresolver=myresolver"
    command: ["sh", "-c", " npm run start"]

networks:
  my_network:
    external: true
