version: "3.7"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioaccesskey
      - MINIO_ROOT_PASSWORD=miniosecretkey
    ports:
      - "9020:9000" # API MinIO
      - "9001:9001" # WebUI MinIO
    networks:
      - my_network
    volumes:
      - minio_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.mia-services.fr`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=myresolver"
      - "traefik.http.services.minio.loadBalancer.server.port=9000"
    command: server /data
    restart: always

volumes:
  minio_data:

networks:
  my_network:
    external: true
